name: Configure AWS Profile

description: Configures an OIDC AWS Role Session as an aws config profile.

branding:
  icon: "cloud"
  color: "orange"

inputs:
  # Additional inputs vs aws-actions/configure-aws-credentials@v3
  profile:
    required: true
    description: Name of profile to be created
  only-profile:
    description: Whether to unset credentials in the environment after writing to the profile. May be useful if you run this action multiple times in the same job
    default: true
    required: false
  whoami:
    description: Whether to run `aws sts get-caller-identity` after configuring the profile
    default: false
    required: false

  # Copied from aws-actions/configure-aws-credentials@v3
  aws-region:
    description: AWS Region, e.g. us-east-2
    required: true
  role-to-assume:
    description: The Amazon Resource Name (ARN) of the role to assume. Use the provided credentials to assume an IAM role and configure the Actions environment with the assumed role credentials rather than with the provided credentials.
    required: false
  aws-access-key-id:
    description: AWS Access Key ID. Provide this key if you want to assume a role using access keys rather than a web identity token.
    required: false
  aws-secret-access-key:
    description: AWS Secret Access Key. Required if aws-access-key-id is provided.
    required: false
  aws-session-token:
    description: AWS Session Token.
    required: false
  web-identity-token-file:
    description: Use the web identity token file from the provided file system path in order to assume an IAM role using a web identity, e.g. from within an Amazon EKS worker node.
    required: false
  role-chaining:
    description: Use existing credentials from the environment to assume a new role, rather than providing credentials as inputs.
    required: false
  audience:
    description: The audience to use for the OIDC provider
    required: false
    default: sts.amazonaws.com
  http-proxy:
    description: Proxy to use for the AWS SDK agent
    required: false
  mask-aws-account-id:
    description: Whether to mask the AWS account ID for these credentials as a secret value. By default the account ID will not be masked
    required: false
  role-duration-seconds:
    description: Role duration in seconds. Default is one hour.
    required: false
  role-external-id:
    description: The external ID of the role to assume.
    required: false
  role-session-name:
    description: "Role session name (default: GitHubActions)"
    required: false
  role-skip-session-tagging:
    description: Skip session tagging during role assumption
    required: false
  inline-session-policy:
    description: Define an inline session policy to use when assuming a role
    required: false
  managed-session-policies:
    description: Define a list of managed session policies to use when assuming a role
    required: false
  unset-current-credentials:
    description: Whether to unset the existing credentials in your runner. May be useful if you run this action multiple times in the same job
    required: false
  disable-retry:
    description: Whether to disable the retry and backoff mechanism when the assume role call fails. By default the retry mechanism is enabled
    required: false
  retry-max-attempts:
    description: The maximum number of attempts it will attempt to retry the assume role call. By default it will retry 12 times
    required: false

outputs:
  aws-account-id:
    description: The AWS account ID for the provided credentials
    value: ${{ steps.aws-credentials.outputs.aws-account-id }}
  aws-access-key-id:
    description: The AWS access key ID for the provided credentials
    value: ${{ steps.aws-credentials.outputs.aws-access-key-id }}
  aws-secret-access-key:
    description: The AWS secret access key for the provided credentials
    value: ${{ steps.aws-credentials.outputs.aws-secret-access-key }}
  aws-session-token:
    description: The AWS session token for the provided credentials
    value: ${{ steps.aws-credentials.outputs.aws-session-token }}

runs:
  using: "composite"
  steps:
    # Unset the variables if they are empty strings, sometimes they do funny things
    - name: Unset empty AWS env vars
      id: unset-empty-env-vars
      shell: bash
      run: |
        if [[ -z "$AWS_ACCESS_KEY_ID" ]]     ; then unset AWS_ACCESS_KEY_ID;     fi
        if [[ -z "$AWS_SECRET_ACCESS_KEY" ]] ; then unset AWS_SECRET_ACCESS_KEY; fi
        if [[ -z "$AWS_SESSION_TOKEN" ]]     ; then unset AWS_SESSION_TOKEN;     fi

    - name: Get AWS Credentials
      id: aws-credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        output-credentials: true

        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-session-token: ${{ inputs.aws-session-token }}
        web-identity-token-file: ${{ inputs.web-identity-token-file }}
        role-chaining: ${{ inputs.role-chaining }}
        audience: ${{ inputs.audience }}
        http-proxy: ${{ inputs.http-proxy }}
        mask-aws-account-id: ${{ inputs.mask-aws-account-id }}
        role-duration-seconds: ${{ inputs.role-duration-seconds }}
        role-external-id: ${{ inputs.role-external-id }}
        role-session-name: ${{ inputs.role-session-name }}
        role-skip-session-tagging: ${{ inputs.role-skip-session-tagging }}
        inline-session-policy: ${{ inputs.inline-session-policy }}
        managed-session-policies: ${{ inputs.managed-session-policies }}
        unset-current-credentials: ${{ inputs.unset-current-credentials }}
        disable-retry: ${{ inputs.disable-retry }}
        retry-max-attempts: ${{ inputs.retry-max-attempts }}

    - name: Save to Profile
      shell: bash
      run: |
        aws configure set --profile ${{ inputs.profile }} region                ${{ inputs.aws-region }}
        aws configure set --profile ${{ inputs.profile }} aws_access_key_id     ${{ steps.aws-credentials.outputs.aws-access-key-id }}
        aws configure set --profile ${{ inputs.profile }} aws_secret_access_key ${{ steps.aws-credentials.outputs.aws-secret-access-key }}
        aws configure set --profile ${{ inputs.profile }} aws_session_token     ${{ steps.aws-credentials.outputs.aws-session-token }}

    # https://github.com/actions/runner/issues/1126 This still leaves behind the env vars
    - name: Set AWS Environment Variables to empty
      id: unset-env-vars
      if: inputs.only-profile
      shell: bash
      run: |
        echo AWS_SECRET_ACCESS_KEY="" >> $GITHUB_ENV
        echo AWS_ACCESS_KEY_ID=""     >> $GITHUB_ENV
        echo AWS_SESSION_TOKEN=""     >> $GITHUB_ENV

    - name: Check auth with Profile
      id: whoami
      if: inputs.whoami
      shell: bash
      run: |
        aws sts --profile ${{ inputs.profile }} get-caller-identity
